stages:
  - push-git

before_script:
  - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
  - git remote set-url origin "https://gitlab-ci-token:${CI_GIT_TOKEN}@${url_host}"

variables:
    ENV_NAME:
      value: "dev"
      description: "environment name"
    ids:
      value: "sh"
      description: "ids"
    application:
      value: "2"
      description: "application"
    version:
      value: "4.3"
      description: "Version"
   

pushgit:
  stage: push-git 
  image: bitnami/git:latest
  script:
    - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
    - git remote set-url origin "https://gitlab-ci-token:${CI_GIT_TOKEN}@${url_host}"
    - git clone ${url_host} -b automation_branch
    - git config user.name "automation"
    - git config user.email "automation@devops.com"
    - | 
      cat << ADD > add.txt
        ids = "$id"
        application = $application
        version = $version
       },
      ADD 
    - ls -lrt
    - cat add.txt
    - sed -i "/abc/r add.txt" ./env/${ENV_NAME}.tfvars
    - rm -rf add.txt
    - git add . 
    - git status
    - git commit -m "added ${id} properties"
    - git push origin HEAD:main